### ISSUE TITLE
Request for more details

### ISSUE THREAD

**Issue by pcrossnz** [Squidex/squidex-docs#17]
Hi there. Would it be possible to enrich this info page? I'd love to install squidex with docker but am having some issues with following these instructions, particularly with setting the domain in the .env file (presume localhost:4000 for local environment?), and making the mongodb database folder, in which I get the following error "No such file or directory". Any help appreciated for someone relatively new to this :)

**Comment by SebastianStehle** [comment]
Sure, it would be good if you join the forum at https://support.squidex.io where I can help you. Then I can improve the docs with the lessons learnt.
